import type { Metadata } from 'next'
import { GeistMono } from 'geist/font/mono'
import './globals.css'
import { Header } from '@/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt" className={GeistMono.className}>
      <body className={`dark:bg-slate-900 dark:text-slate-200 antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
